name: Example Action

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Generate new discussion
        id: create-discussion
        uses: abirismyname/create-discussion@v2.1.0 
        with:
          title: "Test discussion in QA"
          body: |
            Let's see if this works!
          category-name: Q&A
          github-token: ${{ secrets.GITHUB_TOKEN }}
